test

diff --git a/.github/workflows/notify_jira.yml b/.github/workflows/notify_jira.yml
--- a/.github/workflows/notify_jira.yml
+++ b/.github/workflows/notify_jira.yml
@@ -25,6 +25,12 @@ jobs:
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }})
 
+            # Check if curl was successful
+            if [ $? -ne 0 ]; then
+            echo "Failed to fetch commit message."
+            exit 0  # Exit gracefully on curl failure
+          fi
+
           commit_message=$(echo "$commit_info" | jq -r '.commit.message')
 
           # Extract JIRA ID
