test

diff --git a/.github/workflows/notify_jira.yml b/.github/workflows/notify_jira.yml
--- a/.github/workflows/notify_jira.yml
+++ b/.github/workflows/notify_jira.yml
@@ -3,17 +3,6 @@ name: notify_jira
 on:
   workflow_call:
     inputs:
-      be_url:
-        type: string
-        required: true
-      fe_url:
-        type: string
-        required: false
-        default: ""
-      jira_id:
-        type: string
-        required: true
-        default: ""
       status:
         type: string
         required: true
@@ -24,31 +13,106 @@ on:
         default: ""
 
 jobs:
-  send_e2e_result_jira:
-    name: send_e2e_result_jira
+  notify_jira:
     runs-on: ubuntu-latest
-    if: always()
     steps:
-      - name: Prepare JIRA Comment
+      - name: Extract JIRA ID from the commit message
+        id: extract_jira_id
+        run: |
+          # Fetch commit message from the GitHub API
+          commit_info=$(curl -L \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+          https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }})
+
+          commit_message=$(echo "$commit_info" | jq -r '.commit.message')
+
+          # Extract JIRA ID (return code handling)
+          JIRA_ID=$(echo "$commit_message" | grep -oE 'SCFA-[0-9]{1,5}')
+          if [ $? -ne 0 ] || [ -z "$JIRA_ID" ]; then
+            echo "No JIRA ID found in commit message, skipping steps."
+            echo "JIRA_ID_NOT_FOUND=true" >> $GITHUB_ENV
+            exit 0  # Exit gracefully without failing the job
+          else
+            echo "Extracted JIRA ID: $JIRA_ID"
+            echo "JIRA_ID=$JIRA_ID" >> $GITHUB_ENV
+          fi
+
+      - name: Determine the workflow status
+        id: determine_e2e_status
+        if: success() && env.JIRA_ID != ''
         env:
-          BE_BASE_URL: ${{ inputs.be_url }}
-          FE_BASE_URL: ${{ inputs.fe_url }}
-          JIRA_ID: ${{ inputs.jira_id }}
-          WORKFLOW_LINK: ${{ inputs.workflow_link }}
-          STATUS: ${{ inputs.status }}
-          JIRA_USER: ${{ secrets.JIRA_USER }}  # Secret containing JIRA username
-          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}  # Secret containing JIRA API token
+          JIRA_ID: ${{ env.JIRA_ID }}  # Use the extracted JIRA ID
+        run: |
+          STATUS="success"
+          echo "fe_smoke status: ${{ needs.fe_smoke.result }}"
+          echo "fe_core_visual status: ${{ needs.fe_core_visual.result }}"
+          echo "fe_custom_visual status: ${{ needs.fe_custom_visual.result }}"
+          echo "fe_custom status: ${{ needs.fe_custom.result }}"
+          echo "fe_core status: ${{ needs.fe_core.result }}"
+
+          if [[ "${{ needs.fe_smoke.result }}" == "failure" ]] || \
+            [[ "${{ needs.fe_core_visual.result }}" == "failure" ]] || \
+            [[ "${{ needs.fe_custom_visual.result }}" == "failure" ]] || \
+            [[ "${{ needs.fe_custom.result }}" == "failure" ]] || \
+            [[ "${{ needs.fe_core.result }}" == "failure" ]]; then
+            STATUS="failure"
+          fi
+
+          echo "Overall workflow status: $STATUS"
+          echo "STATUS=$STATUS" >> $GITHUB_ENV
+
+      - name: Prepare JIRA Comment
+        id: prepare_jira_comment
+        if: success() && env.JIRA_ID != ''
+        env:
+          JIRA_ID: ${{ env.JIRA_ID }}  # Use the extracted JIRA ID
+          WORKFLOW_LINK: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"  # Link to the workflow run
+          STATUS: ${{ env.STATUS }}  # Use the extracted STATUS
         run: |
           echo "Preparing JIRA comment..."
-          
+
           # Determine the branch name from the Git reference
           GIT_BRANCH=${GITHUB_REF##*/}
-          
+
           # Construct the comment template
-          COMMENT="GHA: E2E Test - ${STATUS} on (this is the git branch: ${GIT_BRANCH})\n"
-          COMMENT+="BE URL: $BE_BASE_URL\n"
-          COMMENT+="FE URL: $FE_BASE_URL\n"
+          COMMENT="E2E Test - ${STATUS} on branch ${GIT_BRANCH}\n"
           COMMENT+="Workflow URL: $WORKFLOW_LINK"
 
-          # Print the comment to the console (for debugging)
-          echo -e "$COMMENT"
+          # Print the comment to the console for debugging
+          echo -e "COMMENT:\n${COMMENT}"
+          echo "COMMENT=$COMMENT" >> $GITHUB_ENV
+
+      - name: Post JIRA Comment
+        id: post_jira_comment
+        if: success() && env.JIRA_ID != ''
+        env:
+          JIRA_ID: ${{ env.JIRA_ID }}  # Use the extracted JIRA ID from the commit message
+          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}  # Jira username from secrets
+          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}  # Jira password from secrets
+          COMMENT: ${{ env.COMMENT }}  # The comment prepared in the previous step
+        run: |
+          echo -e "${JIRA_ID}"
+
+          # Define the JIRA comment API endpoint
+          JIRA_API_URL="https://digital-vic.atlassian.net/rest/api/2/issue/${JIRA_ID}/comment"
+
+          # Post the comment to JIRA using basic auth with username and password
+          response=$(curl -s -w "%{http_code}" -X POST \
+            -H "Content-Type: application/json" \
+            -u "${JIRA_USERNAME}:${JIRA_PASSWORD}" \
+            --data "{\"body\": \"${COMMENT}\"}" \
+            "${JIRA_API_URL}")
+
+          http_code="${response:(-3)}"  # Extract HTTP status code (last 3 characters)
+          response_body="${response:0:-3}"  # The response body
+
+          # Handle the API response
+          if [ "$http_code" -eq 201 ]; then
+            echo "Comment posted successfully to Jira issue ${JIRA_ID}"
+          elif [ "$http_code" -eq 404 ]; then
+            echo "Jira issue ${JIRA_ID} not found. No comment posted."
+          else
+            echo "Failed to post comment to Jira issue ${JIRA_ID}. HTTP Code: $http_code"
+            echo "Response Body: $response_body"
+          fi
